"""Offline HTML template for the M3 monitor report workbench."""

HTML_TEMPLATE_V2 = """<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; img-src data:">
  <title>__TITLE__</title>
  <style>
    :root{color-scheme:light;--ink:#202124;--muted:#67717d;--line:#d8dde3;--paper:#f7f8fa;--panel:#fff;--nav:#f0f3f6;--accent:#16825d;--accent-soft:#e9f6f1;--danger:#a33d45;--danger-soft:#fdebec;--warn:#9a631b;--warn-soft:#fff4df;--focus:#005fcc}
    *{box-sizing:border-box}html{font-family:"Segoe UI","Microsoft YaHei",sans-serif;font-size:15px;letter-spacing:0;background:var(--paper);color:var(--ink)}body{margin:0;min-width:320px}:focus-visible{outline:3px solid var(--focus);outline-offset:2px}.skip{position:absolute;left:.75rem;top:-5rem;z-index:30;padding:.7rem;background:#fff;color:#000}.skip:focus{top:.75rem}
    .report-header{background:#26323d;color:#fff;border-bottom:4px solid var(--accent)}.header-inner{width:min(100%,110rem);margin:auto;padding:1rem 1.25rem}.header-top{display:flex;align-items:center;justify-content:space-between;gap:1rem}h1,h2,h3{margin:0;font-weight:600}h1{font-size:1.25rem;overflow-wrap:anywhere}h2{font-size:1rem}.status{display:inline-flex;min-height:1.7rem;align-items:center;padding:.15rem .5rem;border:1px solid currentColor;border-radius:4px;font-size:.8rem;font-weight:600}.status.partial{color:#ffe0d2}.meta{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:.55rem 1rem;margin:.85rem 0 0}.meta div{min-width:0}.meta dt{color:#cbd5df;font-size:.72rem}.meta dd{margin:.15rem 0 0;overflow-wrap:anywhere;font-size:.86rem}
    main{width:min(100%,110rem);margin:auto;padding:1rem 1.25rem}.notice{margin-bottom:1rem;border-left:4px solid var(--warn);background:var(--warn-soft);padding:.7rem .85rem}.summary{display:grid;grid-template-columns:repeat(4,minmax(9rem,1fr));gap:.5rem;margin-bottom:1rem}.summary-metrics{display:contents}.metric,.summary-filter{border:1px solid var(--line);background:var(--panel);padding:.6rem .7rem;border-radius:4px}.metric strong{display:block;font-size:1.15rem}.metric span,.results,.nav-meta,.coverage{color:var(--muted);font-size:.76rem}.summary-filter{display:grid;align-content:center;gap:.25rem;color:var(--muted);font-size:.76rem}.summary-filter select{width:100%;min-height:2.35rem;padding:.4rem .5rem;border:1px solid #8d98a3;border-radius:4px;background:#fff;color:var(--ink);font:inherit}
    .workbench{position:relative;display:grid;grid-template-columns:220px minmax(0,1fr);min-height:34rem;overflow:hidden;border:1px solid var(--line);background:var(--panel)}.workbook-nav{min-width:0;background:var(--nav);border-right:1px solid var(--line)}.nav-heading{padding:.85rem .9rem .55rem;color:var(--muted);font-size:.76rem}.workbook-list{display:grid;gap:2px;padding:0 .45rem}.workbook-button{display:grid;width:100%;gap:.2rem;padding:.65rem .7rem;color:inherit;text-align:left;background:transparent;border:1px solid transparent;border-radius:4px;cursor:pointer}.workbook-button:hover{background:#e4e9ed}.workbook-button.active{color:#0f684a;background:#dcefe7;border-color:#acd8c7}.workbook-name,.workbook-author{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.workbook-author{color:var(--muted);font-size:.76rem}.workbook-button.active .workbook-author{color:#0f684a}.nav-coverage{margin:.75rem;padding:.65rem 0;border-top:1px solid var(--line)}
    .report-area{display:grid;grid-template-rows:auto minmax(0,1fr);min-width:0}.sheet-tabs{display:flex;min-width:0;overflow-x:auto;padding:0 .65rem;border-bottom:1px solid var(--line);scrollbar-width:thin}.sheet-tab{position:relative;flex:0 0 auto;height:3rem;padding:0 .8rem;color:#59636f;background:transparent;border:0;cursor:pointer}.sheet-tab.active{color:#0f684a;font-weight:600}.sheet-tab.active::after{position:absolute;right:.65rem;bottom:0;left:.65rem;height:2px;content:"";background:var(--accent)}.sheet-count{margin-left:.35rem;color:var(--muted);font-size:.72rem}
    .sheet-content{display:grid;grid-template-rows:auto minmax(0,1fr) auto;min-width:0;min-height:0;padding:.75rem}.sheet-context{display:flex;align-items:center;justify-content:space-between;gap:.75rem;margin-bottom:.55rem}.table-wrap{width:100%;height:clamp(15rem,calc(100vh - 18rem),31rem);overflow:auto;border:1px solid var(--line);background:#fff;cursor:grab;overscroll-behavior:contain;scrollbar-width:thin;touch-action:pan-x pan-y}.table-wrap.dragging{cursor:grabbing;user-select:none}
    table{width:max-content;min-width:100%;border-collapse:separate;border-spacing:0;table-layout:fixed;font-size:.8rem}th,td{width:10.75rem;height:3.9rem;padding:0;vertical-align:middle;border-right:1px solid var(--line);border-bottom:1px solid var(--line)}th{position:sticky;top:0;z-index:3;height:3.7rem;padding:.45rem .6rem;text-align:left;background:#eef1f4;background-clip:padding-box;font-weight:600}th:last-child,td:last-child{border-right:0}tbody tr:last-child td{border-bottom:0}.id-head,.id-cell{position:sticky;left:0;z-index:4;width:7rem;min-width:7rem;max-width:7rem}.id-head{z-index:5;background:#e5e9ed}.id-cell{padding:0 .7rem;background:#f8fafb;font-variant-numeric:tabular-nums;font-weight:600}.field-key,.operation{display:block;margin-top:.2rem;font-size:.7rem}.field-key{overflow:hidden;color:var(--muted);font-family:Consolas,monospace;text-overflow:ellipsis;white-space:nowrap}.operation{font-weight:600}.blank{text-align:center;color:#9aa2ab}
    .change-button,.structure-button{width:calc(100% - .45rem);margin:.225rem;padding:.42rem .5rem;color:inherit;background:var(--accent-soft);border:1px solid #b8dfd1;border-radius:3px;cursor:pointer}.change-button{display:grid;height:calc(100% - .45rem);grid-template-columns:minmax(0,1fr) 1.2rem minmax(0,1fr);align-items:center;text-align:left}.change-button:hover,.structure-button:hover{filter:brightness(.98)}.change-button.selected,.structure-button.selected{border-color:var(--accent);box-shadow:inset 0 0 0 1px var(--accent)}.before,.after{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.before{color:#6c737d;text-decoration:line-through;text-decoration-color:#b26060}.after{color:#0d6648;font-weight:600}.arrow{text-align:center;color:#818791}.structure-button{width:100%;min-height:2rem;margin:.35rem 0 0;text-align:left}.structure-button .operation{margin-top:0}
    .row-added .operation{color:#0f684a}.column-defined{background:var(--warn-soft)}.column-defined .operation{color:var(--warn)}.column-removed,.column-removed .operation,.row-deleted .operation{color:var(--danger)}.column-removed{background:#f8dfe1}.row-added td{background-color:#f1faf6}.row-deleted td,td.column-removed{background-color:var(--danger-soft)}.row-deleted .id-cell{background:#f5dadd}.row-deleted .change-button,td.column-removed .change-button{background:#f8dfe1;border-color:#dfa2a7}.row-deleted .after,td.column-removed .after{color:var(--danger)}
    .empty{display:grid;min-height:15rem;place-items:center;padding:1rem;color:var(--muted);text-align:center}.drawer{position:absolute;top:3rem;right:0;bottom:0;z-index:12;width:min(18rem,calc(100% - 220px));padding:1rem;background:#fff;border-left:1px solid var(--line);box-shadow:-8px 0 20px rgba(30,38,48,.12);transform:translateX(100%);transition:transform .16s ease}.drawer.open{transform:translateX(0)}.drawer-head{display:flex;align-items:center;justify-content:space-between;padding-bottom:.75rem;border-bottom:1px solid var(--line)}.close{display:grid;width:2rem;height:2rem;place-items:center;padding:0;color:inherit;background:transparent;border:0;border-radius:3px;cursor:pointer}.close:hover{background:#eef1f4}.attribution{margin:0}.fact{display:grid;grid-template-columns:6rem minmax(0,1fr);gap:.5rem;padding:.85rem 0;border-bottom:1px solid #eceff2}.fact dt{color:var(--muted)}.fact dd{min-width:0;margin:0;overflow-wrap:anywhere;font-variant-numeric:tabular-nums;font-weight:600}
    details{margin-top:1rem;padding:.75rem;background:#fff;border:1px solid var(--line)}summary{cursor:pointer;font-weight:600}.errors{margin:.7rem 0 0;padding-left:1.25rem}.errors li{margin:.35rem 0;overflow-wrap:anywhere}.coverage{padding:.85rem 0}.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}
    @media(max-width:900px){.meta{grid-template-columns:repeat(2,minmax(0,1fr))}.summary{grid-template-columns:repeat(2,minmax(0,1fr))}.workbench{grid-template-columns:170px minmax(0,1fr)}.drawer{width:calc(100% - 170px)}}
    @media(max-width:560px){.header-inner,main{padding:.75rem}.header-top{align-items:flex-start;flex-direction:column}.meta{grid-template-columns:1fr 1fr}.summary{grid-template-columns:1fr}.workbench{grid-template-columns:140px minmax(0,1fr)}.workbook-list{padding:0 .25rem}.workbook-button{padding:.55rem .4rem}.nav-meta{display:none}.sheet-content{padding:.55rem}.sheet-context{align-items:flex-start;flex-direction:column;gap:.2rem}.drawer{width:calc(100% - 140px);padding:.75rem}.fact{grid-template-columns:1fr;gap:.2rem}}
    @media(prefers-reduced-motion:reduce){*,*::before,*::after{scroll-behavior:auto!important;transition-duration:.01ms!important;animation-duration:.01ms!important;animation-iteration-count:1!important}}
    @media print{.summary-filter,.drawer{display:none}.report-header{color:#000;background:#fff;border-bottom:2px solid #000}.meta dt{color:#444}.summary{grid-template-columns:repeat(3,1fr)}.workbench{display:block;border:0}.workbook-nav,.sheet-tabs{display:none}.table-wrap{height:auto;max-height:none;overflow:visible}table{min-width:0;font-size:8pt}th{position:static}.id-cell{position:static}}
  </style>
</head>
<body data-report-template="m3-workbench-v2.4">
  <a class="skip" href="#main-content">跳到报告内容</a>
  <header class="report-header"><div class="header-inner"><div class="header-top"><h1 id="report-title"></h1><span id="report-status" class="status"></span></div><dl class="meta" id="report-meta"></dl></div></header>
  <main id="main-content" tabindex="-1">
    <div id="partial-notice" class="notice" role="alert" hidden>本报告为部分成功，存在未覆盖数据。请结合错误摘要进行回归。</div>
    <section aria-label="变化摘要与修改人筛选"><div class="summary"><div id="summary-metrics" class="summary-metrics"></div><label class="summary-filter">最终修改人<select id="author"><option value="">全部</option></select></label></div></section>
    <section class="workbench" aria-label="最终净值变化">
      <aside class="workbook-nav"><div class="nav-heading">报告工作簿</div><nav id="workbook-list" class="workbook-list" aria-label="工作簿"></nav><div id="nav-coverage" class="nav-coverage nav-meta"></div></aside>
      <div class="report-area">
        <nav id="sheet-tabs" class="sheet-tabs" aria-label="有修改或错误的 Sheet"></nav>
        <div class="sheet-content"><div class="sheet-context"><h2 id="sheet-title">最终净值变化</h2><span id="result-status" class="results" aria-live="polite" aria-atomic="true"></span></div><div id="table-wrap" class="table-wrap" tabindex="0" aria-label="变化网格，可上下左右滚动"></div><div id="empty" class="empty" hidden></div></div>
      </div>
      <aside id="attribution-drawer" class="drawer" aria-label="最终归因"><div class="drawer-head"><h2>最终归因</h2><button id="drawer-close" class="close" type="button" aria-label="关闭归因侧栏">×</button></div><dl class="attribution"><div class="fact"><dt>最终修改人</dt><dd id="attr-author">-</dd></div><div class="fact"><dt>Revision</dt><dd id="attr-revision">-</dd></div><div class="fact"><dt>修改时间</dt><dd id="attr-time">-</dd></div></dl></aside>
    </section>
    <details id="error-panel"><summary>公开错误摘要（<span id="error-count">0</span>）</summary><ul class="errors" id="errors"></ul></details>
    <footer class="coverage">覆盖范围：可靠导出的 TableCsv 业务字段；不包含未导出字段、Excel 备注、公式、样式、宏和 scope=none 字段。</footer>
  </main>
  <script type="application/json" id="report-data">__REPORT_DATA__</script>
  <script>
  (function(){
    "use strict";
    var report=JSON.parse(document.getElementById("report-data").textContent);
    var labels={field_modified:"字段修改",row_added:"新增行",row_deleted:"删除行",field_removed:"删除字段",field_definition_modified:"字段定义修改"};
    var byId=function(id){return document.getElementById(id)};
    var text=function(tag,value,className){var node=document.createElement(tag);node.textContent=value==null?"-":value;if(className){node.className=className}return node};
    var formatTime=function(value){return value?new Intl.DateTimeFormat("zh-CN",{dateStyle:"medium",timeStyle:"medium",timeZone:"Asia/Shanghai"}).format(new Date(value)):"-"};
    var sideValue=function(side){return side&&side.display_value!=null?String(side.display_value):"-"};
    var isStructure=function(change){return change.change_type==="field_removed"||change.change_type==="field_definition_modified"};
    var structureClass=function(type){return type==="field_removed"?"column-removed":"column-defined"};
    var makeWorkbook=function(name){return{name:name,changes:[],errors:[],sheets:new Map()}};
    var workbooks=new Map();
    var ensureWorkbook=function(name){if(!workbooks.has(name)){workbooks.set(name,makeWorkbook(name))}return workbooks.get(name)};
    var ensureSheet=function(book,name){if(!book.sheets.has(name)){book.sheets.set(name,{name:name,changes:[],errors:[]})}return book.sheets.get(name)};
    report.changes.forEach(function(change){var book=ensureWorkbook(change.workbook);book.changes.push(change);ensureSheet(book,change.sheet_name).changes.push(change)});
    report.errors.forEach(function(error){if(!error.workbook){return}var book=ensureWorkbook(error.workbook);book.errors.push(error);ensureSheet(book,error.sheet_name||"工作簿错误").errors.push(error)});
    var bookList=Array.from(workbooks.values()).sort(function(a,b){var changed=Number(b.changes.length>0)-Number(a.changes.length>0);return changed||a.name.localeCompare(b.name,"zh-CN")});
    var selectedBook=0,selectedSheet=0,selectedButton=null;
    var author=byId("author"),drawer=byId("attribution-drawer"),tableWrap=byId("table-wrap");
    byId("report-title").textContent=report.task_name+" - 版本监控报告";
    byId("report-status").textContent=report.status==="partial"?"部分成功":"成功";byId("report-status").className="status "+report.status;
    [["固定分支",report.branch.label],["报告区间",formatTime(report.interval.start_at)+" 至 "+formatTime(report.interval.end_at)],["Revision",report.revisions.start_revision+" → "+report.revisions.end_revision],["生成时间",formatTime(report.generated_at)]].forEach(function(item){var box=document.createElement("div");box.append(text("dt",item[0]),text("dd",item[1]));byId("report-meta").append(box)});
    byId("partial-notice").hidden=report.status!=="partial";
    [["工作簿",report.summary.changed_workbook_count],["修改人",report.summary.author_count],["错误",report.summary.error_count]].forEach(function(item){var box=text("div","","metric");box.append(text("strong",String(item[1])),text("span",item[0]));byId("summary-metrics").append(box)});
    Array.from(new Set(report.changes.map(function(change){return change.attribution.author}))).sort(function(a,b){return a.localeCompare(b,"zh-CN")}).forEach(function(value){var option=text("option",value);option.value=value;author.append(option)});
    var closeDrawer=function(){drawer.classList.remove("open");if(selectedButton){selectedButton.classList.remove("selected")}selectedButton=null};
    var showAttribution=function(button,change){closeDrawer();selectedButton=button;button.classList.add("selected");byId("attr-author").textContent=change.attribution.author;byId("attr-revision").textContent=change.attribution.revision==null?"-":String(change.attribution.revision);byId("attr-time").textContent=formatTime(change.attribution.changed_at);drawer.classList.add("open")};
    var buildSheetModel=function(sheet){var columns=new Map(),rows=new Map(),displayNames=new Map();sheet.changes.forEach(function(change){if(change.field_name&&change.display_name&&!displayNames.has(change.field_name)){displayNames.set(change.field_name,change.display_name)}});var ensureColumn=function(key,label){if(!columns.has(key)){columns.set(key,{key:key,label:label||displayNames.get(key)||key,structure:null})}else if(label&&columns.get(key).label===key){columns.get(key).label=label}return columns.get(key)};sheet.changes.forEach(function(change){if(change.field_name&&change.change_type!=="field_added"){var column=ensureColumn(change.field_name,change.display_name);if(isStructure(change)){column.structure=change}}if(change.row_key==null){return}if(!rows.has(change.row_key)){rows.set(change.row_key,{key:change.row_key,state:"",event:null,cells:new Map()})}var row=rows.get(change.row_key);if(change.change_type==="field_modified"){ensureColumn(change.field_name,change.display_name);row.cells.set(change.field_name,{before:sideValue(change.source),after:sideValue(change.target),change:change})}else if(change.change_type==="row_added"||change.change_type==="row_deleted"){row.state=change.change_type==="row_added"?"row-added":"row-deleted";row.event=change;var values=change.change_type==="row_added"?change.target.row_values:change.source.row_values;Object.keys(values||{}).forEach(function(key){if(key.toLocaleLowerCase("en-US")===change.primary_key_field.toLocaleLowerCase("en-US")){return}ensureColumn(key,displayNames.get(key)||key);row.cells.set(key,{before:change.change_type==="row_added"?"-":String(values[key]),after:change.change_type==="row_added"?String(values[key]):"-",change:change})})}});return{columns:Array.from(columns.values()),rows:Array.from(rows.values()).sort(function(a,b){return a.key.localeCompare(b.key,"zh-CN",{numeric:true})})}};
    var currentSheet=function(){var book=bookList[selectedBook];return book?Array.from(book.sheets.values()).sort(function(a,b){return a.name.localeCompare(b.name,"zh-CN")})[selectedSheet]:null};
    var finalWorkbookAuthor=function(book){if(book.changes.some(function(change){return change.attribution.status==="unresolved"})){return"未知"}var latest=null;book.changes.forEach(function(change){var attr=change.attribution,revision=attr.revision==null?-1:Number(attr.revision),changedAt=attr.changed_at||"";if(!latest||revision>latest.revision||revision===latest.revision&&changedAt>latest.changedAt){latest={author:attr.author,revision:revision,changedAt:changedAt}}});return latest?latest.author:"未知"};
    var renderBooks=function(){var host=byId("workbook-list");host.replaceChildren();bookList.forEach(function(book,index){var button=document.createElement("button");button.type="button";button.className="workbook-button"+(index===selectedBook?" active":"");button.setAttribute("aria-pressed",index===selectedBook?"true":"false");button.append(text("span",book.name,"workbook-name"),text("span",book.changes.length+" 项变化"+(book.errors.length?" · "+book.errors.length+" 个错误":""),"nav-meta"),text("span",finalWorkbookAuthor(book),"workbook-author"));button.addEventListener("click",function(){selectedBook=index;selectedSheet=0;closeDrawer();renderBooks();renderSheets();renderGrid()});host.append(button)});var remainder=Math.max(0,report.summary.workbook_count-bookList.length);byId("nav-coverage").textContent=remainder?"另有 "+remainder+" 个已比较工作簿没有最终净变化或公开错误。":"已列出本报告可识别的全部工作簿。"};
    var renderSheets=function(){var host=byId("sheet-tabs");host.replaceChildren();var book=bookList[selectedBook];if(!book){return}Array.from(book.sheets.values()).sort(function(a,b){return a.name.localeCompare(b.name,"zh-CN")}).forEach(function(sheet,index){var button=document.createElement("button");button.type="button";button.className="sheet-tab"+(index===selectedSheet?" active":"");button.setAttribute("aria-selected",index===selectedSheet?"true":"false");button.append(document.createTextNode(sheet.name),text("span",String(sheet.changes.length),"sheet-count"));button.addEventListener("click",function(){selectedSheet=index;closeDrawer();renderSheets();renderGrid()});host.append(button)})};
    var appendChangeButton=function(cell,item){var button=document.createElement("button");button.type="button";button.className="change-button";button.setAttribute("aria-label",item.change.change_type+"："+item.before+" 变为 "+item.after);button.append(text("span",item.before,"before"),text("span","→","arrow"),text("span",item.after,"after"));button.addEventListener("click",function(){showAttribution(button,item.change)});cell.append(button)};
    var renderGrid=function(){tableWrap.replaceChildren();var sheet=currentSheet();if(!sheet){byId("sheet-title").textContent="无最终净变化";byId("result-status").textContent="";byId("empty").textContent="本报告没有可展示的工作簿变化。";byId("empty").hidden=false;return}var model=buildSheetModel(sheet),authorValue=author.value;var rows=model.rows.filter(function(row){return!authorValue||Array.from(row.cells.values()).some(function(item){return item.change.attribution.author===authorValue})});byId("sheet-title").textContent=sheet.name;byId("result-status").textContent=rows.length+" 个主键 · "+sheet.changes.length+" 项最终净变化";var structural=model.columns.filter(function(column){return column.structure});if(!rows.length&&!structural.length){byId("empty").textContent=sheet.errors.length?"此 Sheet 只有公开错误，没有可靠变化可展示。":"没有符合当前筛选条件的变化。";byId("empty").hidden=false;return}byId("empty").hidden=true;var table=document.createElement("table"),caption=text("caption","版本监控最终净值变化网格","sr-only"),thead=document.createElement("thead"),head=document.createElement("tr"),idHead=text("th","主键 ID","id-head");idHead.scope="col";head.append(idHead);model.columns.forEach(function(column){var th=document.createElement("th");th.scope="col";if(column.structure){th.classList.add(structureClass(column.structure.change_type))}th.append(text("span",column.label),text("span",column.key,"field-key"));if(column.structure){var button=document.createElement("button");button.type="button";button.className="structure-button";button.append(text("span",labels[column.structure.change_type],"operation"));button.addEventListener("click",function(){showAttribution(button,column.structure)});th.append(button)}head.append(th)});thead.append(head);table.append(caption,thead);var body=document.createElement("tbody");rows.forEach(function(row){var tr=document.createElement("tr");if(row.state){tr.className=row.state}var id=text("td",row.key,"id-cell");if(row.state){id.append(text("span",row.state==="row-added"?"新增行":"删除行","operation"))}tr.append(id);model.columns.forEach(function(column){var td=document.createElement("td");if(column.structure){td.classList.add(structureClass(column.structure.change_type))}var item=row.cells.get(column.key);if(item){appendChangeButton(td,item)}else{td.classList.add("blank");td.textContent="-"}tr.append(td)});body.append(tr)});if(!rows.length&&structural.length){var tr=document.createElement("tr");tr.append(text("td","-","id-cell"));model.columns.forEach(function(column){var td=document.createElement("td");if(column.structure){td.classList.add(structureClass(column.structure.change_type));var button=document.createElement("button");button.type="button";button.className="structure-button";button.append(text("span",labels[column.structure.change_type],"operation"));button.addEventListener("click",function(){showAttribution(button,column.structure)});td.append(button)}else{td.className="blank";td.textContent="-"}tr.append(td)});body.append(tr)}table.append(body);tableWrap.append(table)};
    author.addEventListener("change",renderGrid);byId("drawer-close").addEventListener("click",closeDrawer);
    var drag=null,ignoreClick=false;tableWrap.addEventListener("pointerdown",function(event){if(event.pointerType!=="mouse"||event.button!==0){return}drag={id:event.pointerId,x:event.clientX,y:event.clientY,left:tableWrap.scrollLeft,top:tableWrap.scrollTop,moved:false}});window.addEventListener("pointermove",function(event){if(!drag||event.pointerId!==drag.id){return}var dx=event.clientX-drag.x,dy=event.clientY-drag.y;if(!drag.moved&&Math.hypot(dx,dy)>5){drag.moved=true;tableWrap.classList.add("dragging")}if(drag.moved){tableWrap.scrollLeft=drag.left-dx;tableWrap.scrollTop=drag.top-dy;event.preventDefault()}});window.addEventListener("pointerup",function(event){if(!drag||event.pointerId!==drag.id){return}if(drag.moved){ignoreClick=true;window.setTimeout(function(){ignoreClick=false},0)}tableWrap.classList.remove("dragging");drag=null});tableWrap.addEventListener("click",function(event){if(ignoreClick){event.preventDefault();event.stopPropagation()}},true);
    byId("error-count").textContent=String(report.errors.length);byId("error-panel").hidden=report.errors.length===0;report.errors.forEach(function(error){byId("errors").append(text("li",error.message+(error.workbook?" · "+error.workbook:"")+(error.sheet_name?" / "+error.sheet_name:"")))});
    renderBooks();renderSheets();renderGrid();
  }());
  </script>
</body>
</html>
"""
